version: '3'

services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "wordpress"
    volumes:
      - mysql_data:/var/lib/mysql
  wordpress:
    image: "wordpress:latest"
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql_data:
  wordpress_data:
