version: "3.1"

services:
  wordpress:
    container_name: wordpress_container
    hostname: wordpress
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress-cms
      WORDPRESS_DB_PASSWORD: wordpress-cms
      WORDPRESS_DB_NAME: wordpress-cms
    networks:
      - wordpress_network

  db:
    container_name: db_container
    hostname: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress-cms
      MYSQL_USER: wordpress-cms
      MYSQL_PASSWORD: wordpress-cms
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    networks:
      - wordpress_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    hostname: nginx
    ports:
      - 443:443
    volumes:
      - ./app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./snippets:/etc/nginx/snippets
      - ./ssl:/etc/nginx/ssl
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
