version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress-cms
      WORDPRESS_DB_USER: martina
      WORDPRESS_DB_PASSWORD: example

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress-cms
      MYSQL_USER: martina
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
