version: '3.9'

services:
  # =app
  app:
    image: "wordpress:latest"
    container_name: "${APP_NAME}"
    #command: "tail -f /dev/null"
    #entrypoint: "tail -f /dev/null"
    hostname: "${APP_NAME}.local"
    ports:
      - "8080:80"
    #network_mode: "host"
    #cap_add:
    #  - NET_ADMIN
    #security_opt:
    #  - seccomp:unconfined
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

  # =db
  db:
    image: "mysql:8"
    container_name: "${APP_NAME}-db"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${APP_DB_DATABASE}
      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=${APP_DB_USERNAME}
      - MYSQL_PASSWORD=${APP_DB_PASSWORD}
    volumes:
      - "db:/var/lib/mysql"
    hostname: "${APP_NAME}-db.local"
    ports:
      - "3306:3306"
    networks:
      default:
        ipv4_address: "${APP_DB_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}-db.local"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"


# =networks
networks:
  default:
    name: "vpc_cms"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_<app-name>:
#    external: true

# =volumes
volumes:
  db: