version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress-cms
      WORDPRESS_DB_PASSWORD: wordpress-cms
      WORDPRESS_DB_NAME: wordpress-cms

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wordpress-cms
      MYSQL_USER: wordpress-cms
      MYSQL_PASSWORD: wordpress-cms
      MYSQL_RANDOM_ROOT_PASSWORD: '1'