version: '3.8'

services:
  wordpress:
    image: wordpress
    ports:
      - "8000:80"  # Mappa la porta 80 del container di WordPress alla porta 8000 del host
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
   depends_on:
      - mysql 
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
